--- 
abstract: installs all non-Apache prereqs for Apache2
author: Kevin W. Henwood <Khen1950fx@aol.com>
build_requires: 
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Task-Apache2-Dependencies
no_index: 
  directory: 
    - inc
    - t
requires: 
  AI::Categorizer: 0
  Algorithm::Dependency: 0
  Apache::DBI: 0
  AppConfig: 0
  Archive::Any: 0
  Archive::Tar: 0
  Archive::Zip: 0
  Array::PAT: 0
  Authen::Radius: 0
  Authen::SASL: 0
  Authen::Smb: 0
  Authen::TypeKey: 0
  AutoLoader: 0
  BerkeleyDB: 0
  BitTorrent: 0
  CGI: 0
  CGI::Ajax: 0
  CGI::Cookie: 0
  CGI::Minimal: 0
  CGI::Session: 0
  CGI::Session::Driver: 0
  CGI::Untaint: 0
  CGI::Untaint::date: 0
  CGI::Untaint::email: 0
  CGI::Utils: 0
  CGI::okTemplate: 0
  CPAN::DistnameInfo: 0
  CSS: 0
  CSS::Tiny: 0
  Cache::Cache: 0
  Cache::FastMmap: 0
  Cache::Memcached: 0
  Carp::Assert: 0
  Carp::Assert::More: 0
  Class::Accessor: 0
  Class::Autouse: 0
  Class::Bits: 0
  Class::Container: 0
  Class::DBI::AbstractSearch: 0
  Class::DBI::Loader: 0
  Class::DBI::Loader::Relationship: 0
  Class::DBI::Pager: 0
  Class::DBI::Plugin::RetrieveAll: 0
  Class::DBI::Plugin::Type: 0
  Class::Data::Inheritable: 0
  Class::Date: 0
  Class::ErrorHandler: 0
  Class::ISA: 0
  Class::Inner: 0
  Class::InsideOut: 0
  Class::Inspector: 0
  Class::Member: 0
  Class::Singleton: 0
  Class::Struct: 0
  Class::Struct::FIELDS: 0
  Class::Trigger: 0
  Class::Util: 0
  Class::Virtual: 0
  Compress::LeadingBlankSpaces: 0
  Compress::Raw::Zlib: 0
  Compress::Zlib: 0
  Config::Auto: 0
  Config::General: 0
  Config::IniFiles: 0
  Config::Tiny: 0
  Convert::RACE: 0
  Crypt::Blowfish: 0
  Crypt::Blowfish_PP: 0
  Crypt::CAST5: 0
  Crypt::CBC: 0
  Crypt::PasswdMD5: 0
  Crypt::Rijndael: 0
  Cwd: 0
  DBD::CSV: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBI: 0
  DBI::Const::GetInfo::ODBC: 0
  DBIx::ContextualFetch: 0
  DBIx::Transaction: 0
  DB_File: 0
  DB_File::Lock: 0
  Data::ClearSilver::HDF: 0
  Data::Dumper: 0
  Data::FormValidator: 0
  Data::HexDump: 0
  Data::Page: 0
  Data::Serializer: 0
  Date::Calc: 0
  Date::Format: 0
  Date::Manip: 0
  Date::Parse: 0
  Date::Simple: 0
  DateTime: 0
  DateTime::Format::Mail: 0
  DateTime::Format::W3CDTF: 0
  DateTime::Locale: 0
  DateTime::TimeZone: 0
  Devel::DProf: 0
  Devel::StackTrace: 0
  Devel::Symdump: 0
  Digest: 0
  Digest::CRC: 0
  Digest::HMAC_MD5: 0
  Digest::MD5: 0
  Digest::SHA: 0
  Digest::SHA1: 0
  Digest::SHA::PurePerl: 0
  Digest::base: 0
  Email::Find: 0
  Email::Valid: 0
  Errno: 0
  Error: 0
  Exception::Class: 0
  Exporter::Lite: 0
  ExtUtils::AutoInstall: 0
  ExtUtils::MakeMaker: 0
  ExtUtils::Manifest: 0
  ExtUtils::ModuleMaker: 0
  ExtUtils::XSBuilder::ParseSource: 0
  File::BaseDir: 0
  File::Basename::Object: 0
  File::Compare: 0
  File::Copy::Recursive: 0
  File::CounterFile: 0
  File::DesktopEntry: 0
  File::FDkeeper: 0
  File::FDpasser: 0
  File::Find::Rule: 0
  File::Find::Rule::Filesys::Virtual: 0
  File::Find::Rule::ImageSize: 0
  File::Find::Rule::Perl: 0
  File::Flat: 0
  File::MMagic: 0
  File::MimeInfo::Magic: 0
  File::NCopy: 0
  File::NFSLock: 0
  File::Path: 0
  File::Pid: 0
  File::Remove: 0
  File::Slurp: 0
  File::Tail: 0
  File::Temp: 0
  Filesys::Virtual: 0
  Filesys::Virtual::Plain: 0
  Filter::EOF: 0
  Filter::Util::Call: 0
  FindBin::Real: 0
  FindBin::libs: 0
  Formatter::HTML::Preformatted: 0
  Formatter::HTML::Textile: 0
  GD: 0
  GD::Graph::Data: 0
  GD::Graph::Error: 0
  GD::Text::Align: 0
  GSSAPI: 0
  GTop: 0
  Getopt::ArgvFile: 0
  Getopt::Long: 0
  HTML::Clean: 0
  HTML::Entities: 0
  HTML::FillInForm: 0
  HTML::Lint: 0
  HTML::Mason: 0
  HTML::Parser: 0
  HTML::SimpleParse: 0
  HTML::StickyQuery: 0
  HTML::Tagset: 0
  HTML::Template: 0
  HTML::Template::Set: 0
  HTML::Template::XPath: 0
  HTML::Tested: 0
  HTML::Tested::ClassDBI: 0
  HTML::TextToHTML: 0
  HTML::WWWTheme: 0
  HTTP::DAV: 0
  HTTP::DAVServer: 0
  HTTPD::UserAdmin: 0
  Heap: 0
  Hook::LexWrap: 0
  I18N::Charset: 0
  I18N::LangTags: 0
  IO: 0
  IO::CaptureOutput: 0
  IO::Compress::Base: 0
  IO::Compress::Base::Common: 0
  IO::Compress::Gzip: 0
  IO::Compress::Gzip::Constants: 0
  IO::Handle::Record: 0
  IO::String: 0
  IO::Stringy: 0
  IO::Tty: 0
  IO::Uncompress::Base: 0
  IO::Uncompress::Gunzip: 0
  IO::Util: 0
  IO::Zlib: 0
  IPC::Cache: 0
  IPC::Run: 0
  IPC::ShareLite: 0
  IPC::Shareable: 0
  Ima::DBI: 0
  Image::GD::Thumbnail: 0
  Image::Imlib2: 0
  Image::Info: 0
  Image::LibRSVG: 0
  Image::Size: 0
  Inline::MakeMaker: 0
  JSON: 0
  JSON::XS: 0
  JUNOS::Access: 0
  JavaScript::Autocomplete::Backend: 0
  Jemplate: 0
  LWP: 0
  LWP::Simple::Cookies: 0
  LWP::Simple::Post: 0
  Lingua::EN::Inflect: 0
  Lingua::GL::Stemmer: 0
  Lingua::PT::Stemmer: 0
  Lingua::Stem: 0
  Lingua::Stem::Fr: 0
  Lingua::Stem::It: 0
  Lingua::Stem::Snowball::Da: 0
  Lingua::Stem::Snowball::No: 0
  Lingua::Stem::Snowball::Se: 0
  Lingua::StopWords: 0
  List::MoreUtils: 0
  Locale::Country: 0
  Locale::Maketext: 0
  Locale::gettext: 0
  Log::Agent: 0
  Log::Agent::Driver::Apache: 0
  Log::Agent::Logger: 0
  Log::Agent::Message: 0
  Log::Trace: 0
  MIME::Base64: 0
  MIME::Entity: 0
  MIME::Lite: 0
  MIME::QuotedPrint: 0
  MIME::Types: 0
  MLDBM: 0
  MLDBM::Sync::SDBM_File: 0
  MP3::Info: 0
  Mail::Address: 0
  Mail::Field: 0
  Mail::Header: 0
  Mail::Internet: 0
  Mail::Mailer: 0
  Math::Base85: 0
  Math::BigInt: 0
  Math::BigInt::FastCalc: 0
  Math::BigInt::GMP: 0
  Math::BigInt::Pari: 0
  Math::BigRat: 0
  Math::Trig: 0
  Maypole::Plugin::Config::Apache: 0
  Memoize: 0
  Module::Build: 0
  Module::Build::Compat: 0
  Module::Find: 0
  Module::Install: 0
  Module::Signature: 0
  Modwheel: 0
  MogileFS::Client: 0
  MogileFS::Client::FilePaths: 0
  Net::BitTorrent::File: 0
  Net::BitTorrent::PeerPacket: 0
  Net::Cmd: 0
  Net::DAV::Server: 0
  Net::DNS: 0
  Net::IPv4Addr: 0
  Net::LDAP: 0
  Net::PH: 0
  Net::POP3_auth: 0
  Net::SMTP: 0
  Net::SNMP: 0
  Number::Compare: 0
  Number::Compare::Date: 0
  PAR::Dist: 0
  PHP::DateTime: 0
  PHP::Functions::Mail: 0
  PHP::Include: 0
  PHP::MySource::Session: 0
  PHP::Serialization: 0
  PHP::Session: 0
  PHP::Session::DB: 0
  PHP::Session::DBI: 0
  POE: 0
  PPI: 0
  PPI::HTML: 0
  Params::Util: 0
  Params::Validate: 0
  Parse::RecDescent: 0
  Parse::Yapp::Driver: 0
  Path::Class: 0
  Perl::AtEndOfScope: 0
  Perl::MinimumVersion: 0
  Perl::Tidy: 0
  Perl::WhichPhase: 0
  Pod::AxPoint: 0
  Pod::Escapes: 0
  Pod::Man: 0
  Pod::SAX: 0
  Pod::Simple: 0
  Pod::Spell: 0
  Pod::Tests: 0
  Pod::Text: 0
  Pod::Tree: 0
  Pod::Usage: 0
  Pod::WikiDoc: 0
  Pod::Xhtml: 0
  Rcs: 0
  Readonly: 0
  Regexp::MultiLanguage::PHP: 0
  ResourcePool: 0
  ResourcePool::Resource::DBI: 0
  ResourcePool::Resource::Net::LDAP: 0
  SDBM_File: 0
  SQL::Abstract: 0
  SQL::Abstract::Limit: 0
  SQL::Eval: 0
  SQL::Parser: 0
  SQL::Statement: 0
  SQL::Statement::Functions: 0
  Safe: 0
  Scalar::Util: 0
  Servlet: 0
  Socket6: 0
  Sort::Versions: 0
  Statistics::Contingency: 0
  String::CRC: 0
  String::CRC32: 0
  String::CRC::Cksum: 0
  String::LRC: 0
  Symbol::Table: 0
  Syntax::Highlight::Perl: 0
  Sys::Hostname::Long: 0
  Sys::Proctitle: 0
  Task::Weaken: 0
  Template: 0
  Template::Plugin::Class: 0
  Template::Plugin::Page: 0
  Template::Trivial: 0
  Test: 0
  Test::Assertions: 0
  Test::Builder: 0
  Test::ClassAPI: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::File::Cleaner: 0
  Test::File::Find::Rule: 0
  Test::Group: 0
  Test::Harness: 0
  Test::MinimumVersion: 0
  Test::MockModule: 0
  Test::MockObject: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Object: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Script: 0
  Test::Signature: 0
  Test::Spelling: 0
  Test::SubCalls: 0
  Test::Tester: 0
  Test::Warn: 0
  Text::Aspell: 0
  Text::Balanced: 0
  Text::CSV_XS: 0
  Text::Diff: 0
  Text::German: 0
  Text::Glob: 0
  Text::Iconv: 0
  Text::ParseWords: 0
  Text::Template: 0
  Text::Template::Simple: 0
  Text::Textile: 0
  Text::Unidecode: 0
  Text::VimColor: 0
  Text::Wrap: 0
  Tie::DirHandle: 0
  Tie::Handle::CSV: 0
  Tie::Handle::HTTP: 0
  Tie::Handle::ToMemory: 0
  Tie::Hash::CustomStorage: 0
  Tie::Scalar: 0
  Tie::Simple: 0
  Time::HiRes: 0
  Time::Local: 0
  Time::Local::Extended: 0
  Time::ParseDate: 0
  Time::Period: 0
  Time::Piece: 0
  Time::Progress: 0
  Time::Zone: 0
  Tree::DAG_Node: 0
  UNIVERSAL::can: 0
  UNIVERSAL::isa: 0
  UNIVERSAL::moniker: 0
  UNIVERSAL::require: 0
  URI: 0
  URI::Find: 0
  URI::Find::Simple: 0
  Unicode::String: 0
  WWW::Google::SiteMap: 0
  WWW::Mechanize: 0
  WeakRef: 0
  Wombat: 0
  XML::DOM: 0
  XML::Dumper: 0
  XML::EasyOBJ: 0
  XML::LibXML: 0
  XML::LibXML::Common: 0
  XML::LibXSLT: 0
  XML::NamespaceSupport: 0
  XML::Parser: 0
  XML::Parser::PerlSAX: 0
  XML::RSS: 0
  XML::RegExp: 0
  XML::SAX: 0
  XML::SAX::Base: 0
  XML::SAX::ExpatXS: 0
  XML::SAX::Writer: 0
  XML::Sablotron: 0
  XML::Simple: 0
  XML::Twig: 0
  XML::XSLT: 0
  XSLoader: 0
  YAML: 0
  YAML::Syck: 0
  bignum: 0
  enum: 0
  ex::override: 0
  load: 0
  namespace::clean: 0
  perl: 5.6.0
  version: 0
version: 0.02
